version: '3.8'

services:
  app:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - MONGO_URI=mongodb://mongo:27017/taskmanager
      - JWT_SECRET=your_super_secret_jwt_key_here
      - ADMIN_INVITE_TOKEN=your_admin_invite_token_here
      - CLIENT_URL=http://localhost:3001
    depends_on:
      - mongo
    volumes:
      - ./uploads:/app/uploads

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
